[2024-04-05T16:09:17.680+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-04-05T16:09:17.733+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-04-04T00:00:00+00:00 [queued]>
[2024-04-05T16:09:17.741+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-05T16:09:17.747+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-05T16:09:17.753+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-05T16:09:19.745+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-04-04 00:00:00+00:00
[2024-04-05T16:09:19.856+0000] {standard_task_runner.py:55} INFO - Started process 3257 to run task
[2024-04-05T16:09:19.952+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2024-04-04T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpni_ms_x1']
[2024-04-05T16:09:19.960+0000] {standard_task_runner.py:83} INFO - Job 112: Subtask create_table
[2024-04-05T16:09:20.934+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2024-04-04T00:00:00+00:00 [running]> on host a868c0c748e3
[2024-04-05T16:09:28.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-04T00:00:00+00:00
[2024-04-05T16:09:28.370+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-04-05T16:09:28.393+0000] {sql.py:315} INFO - Running statement: 
			CREATE TABLE IF NOT EXISTS users (
				firstname TEXT NOT NULL,
				lastname TEXT NOT NULL,
				country TEXT NOT NULL,
				username TEXT NOT NULL,
				password TEXT NOT NULL,
				email TEXT NOT NULL
			);
		, parameters: None
[2024-04-05T16:09:28.402+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-04-05T16:09:28.441+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240404T000000, start_date=20240405T160917, end_date=20240405T160928
[2024-04-05T16:09:29.398+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-04-05T16:09:30.375+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
